name: Build Linux ARM64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        arch: [aarch64]
        include:
          - arch: aarch64
            cpu: cortex-a72
            base_image: https://dietpi.com/downloads/images/DietPi_RPi5-ARMv8-Bookworm.img.xz
            deb: arm64
            appimage: aarch64

    steps:
      - uses: actions/checkout@v3

      - name: Cache rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-on-failure: true

      - name: Build app
        uses: pguyot/arm-runner-action@v2.6.5
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: no
          commands: |
            # Prevent Rust from complaining about $HOME not matching eid home
            export HOME=/root

            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

            # Install setup prerequisites
            apt-get update -y --allow-releaseinfo-change
            apt-get autoremove -y
            apt-get install -y --no-install-recommends --no-install-suggests curl libwebkit2gtk-4.0-dev build-essential libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf libfuse2 file
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . "$HOME/.cargo/env"
            curl -fsSL https://deb.nodesource.com/setup_lts.x | bash
            apt-get install -y nodejs

            # Install pnpm
            npm install -g pnpm

            # 修改 tauri.conf.json 设置目标格式
            cd /tmp/repository
            sed -i 's/"targets": "all"/"targets": ["deb", "appimage"]/' src-tauri/tauri.conf.json
            cat src-tauri/tauri.conf.json

            # Install dependencies
            pnpm install --no-frozen-lockfile

            # Build frontend
            pnpm build

            # Install Tauri CLI
            cargo install tauri-cli

            # Build the application
            cd src-tauri
            cargo tauri build --verbose

      - name: Get app version
        run: echo "APP_VERSION=$(jq -r .version src-tauri/tauri.conf.json)" >> $GITHUB_ENV

      - name: Get app name
        run: echo "APP_NAME=$(jq -r .productName src-tauri/tauri.conf.json)" >> $GITHUB_ENV

      - name: List build files
        run: |
          ls -la ${{ github.workspace }}/src-tauri/target/release/bundle/deb/ || true
          ls -la ${{ github.workspace }}/src-tauri/target/release/bundle/appimage/ || true

      - name: Upload deb bundle
        uses: actions/upload-artifact@v3
        with:
          name: Debian ARM64 Bundle
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/deb/*.deb

      - name: Upload appimage bundle
        uses: actions/upload-artifact@v3
        with:
          name: AppImage ARM64 Bundle
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/appimage/*.AppImage