name: Build Linux ARM64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libsoup2.4-dev \
            libjavascriptcoregtk-4.0-dev
            
      - name: Configure cross-compilation environment
        run: |
          # 创建必要的目录
          sudo mkdir -p /usr/aarch64-linux-gnu/lib/pkgconfig
          
          # 设置环境变量
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build frontend
        run: pnpm build
      
      - name: Setup cargo-tauri
        run: cargo install tauri-cli
      
      - name: Modify Tauri config
        run: |
          # 修改 tauri.conf.json 以使用 deb 和 appimage 打包格式
          sed -i 's/"targets": "all"/"targets": ["deb", "appimage"]/' src-tauri/tauri.conf.json
          # 减少依赖，移除不必要的插件
          cat src-tauri/tauri.conf.json
      
      - name: Modify Cargo.toml
        run: |
          # 修改 Cargo.toml 使用 libsoup2.4 而非 libsoup3
          cd src-tauri
          if grep -q 'features = \["api-all"\]' Cargo.toml; then
            sed -i 's/features = \["api-all"\]/features = \["api-all", "libsoup"\]/' Cargo.toml
          else
            sed -i 's/features = \[\]/features = \["libsoup"\]/' Cargo.toml
          fi
          cat Cargo.toml
      
      - name: Build Linux ARM64 package
        run: |
          # 配置交叉编译环境
          mkdir -p ~/.cargo
          echo '[target.aarch64-unknown-linux-gnu]' > ~/.cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml
          
          # 设置环境变量
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
          export CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
          
          # 打印环境变量以便调试
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
          echo "PKG_CONFIG_ALLOW_CROSS=$PKG_CONFIG_ALLOW_CROSS"
          
          # 构建
          cd src-tauri
          cargo tauri build --target aarch64-unknown-linux-gnu --verbose
      
      - name: Upload Linux ARM64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-packages
          path: |
            src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/deb/*.deb
            src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/appimage/*.AppImage 